[build]
  publish = "."
  command = "npm install && npm run build"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/piece/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true

[template.environment]
  NETLIFY_CMS_BACKEND = "git-gateway"
